import os

IS_DOCKER = os.getenv("IS_DOCKER")
JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY")
GOOGLE_CLIENT_ID = os.getenv("VITE_GOOGLE_CLIENT_ID")
VITE_GITHUB_CLIENT_ID = os.getenv("VITE_GITHUB_CLIENT_ID")
GITHUB_CLIENT_SECRET = os.getenv("GITHUB_CLIENT_SECRET")
POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")

